### ISSUE TITLE
Creates Sphinx documentation for Beyond

### ISSUE THREAD

**Issue by LesleyLai** [LesleyLai/Beyond-Game-Engine#21]
Create documentation for Beyond with [Sphinx](http://www.sphinx-doc.org) and [breathe](https://breathe.readthedocs.io/en/latest/). Please look at [awesome-sphinxdoc](https://github.com/yoloseem/awesome-sphinxdoc).

- Research how to write documentation in Sphinx
- Research useful Sphinx extensions
- [ ] Instruction of building documentation in readme
- [ ] Design structure of the documentation
- [ ] Design style of the documentation

**Comment by LesleyLai** [comment]
Give up
